def builder():
    context = {}
    context['@type'] = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
    context['label'] = "http://www.w3.org/2000/01/rdf-schema#label"
    context['ARG_2000029'] = "http://purl.obolibrary.org/obo/ARG_2000029"
    context['ARG_2000028'] = "http://purl.obolibrary.org/obo/ARG_2000028"
    context['orcidId'] = "http://vivoweb.org/ontology/core#orcidId"
    context['holdsAccount'] = "http://xmlns.com/foaf/0.1/holdsAccount"
    context['givenName'] = "http://www.w3.org/2006/vcard/ns#givenName"
    context['familyName'] = "http://www.w3.org/2006/vcard/ns#familyName"
    context['hasName'] = "http://www.w3.org/2006/vcard/ns#hasName"
    context['bearerof'] = "http://purl.obolibrary.org/obo/RO_0000053"
    context['inhersin'] = "http://purl.obolibrary.org/obo/RO_0000052"
    context['roleContributesTo'] = "http://vivoweb.org/ontology/core#roleContributesTo"
    context['contributingRole'] = "http://vivoweb.org/ontology/core#contributingRole"
    context['hasParticipant'] = "http://purl.obolibrary.org/obo/RO_0000057"
    context['participatesIn'] = "http://purl.obolibrary.org/obo/RO_0000056"
    context['keywords'] = "http://vivoweb.org/ontology/core#freetextKeyword"
    context['doi'] = "http://purl.org/ontology/bibo/doi"
    context['endPage'] = "http://purl.org/ontology/bibo/pageEnd"
    context['startPage'] = "http://purl.org/ontology/bibo/pageStart"
    context['volume'] = "http://purl.org/ontology/bibo/volume"
    context['issue'] = "http://purl.org/ontology/bibo/issue"
    context['relates'] = "http://vivoweb.org/ontology/core#relates"
    context['relatedBy'] = "http://vivoweb.org/ontology/core#relatedBy"
    context['hasSubjectArea'] = "http://vivoweb.org/ontology/core#hasSubjectArea"
    context['subjectAreaOf'] = "http://vivoweb.org/ontology/core#subjectAreaOf"
    context['hasResearchArea'] = "http://vivoweb.org/ontology/core#hasResearchArea"
    context['researchAreaOf'] = "http://vivoweb.org/ontology/core#researchAreaOf"
    context['governingAuthorityFor'] = "http://vivoweb.org/ontology/core#governingAuthorityFor"
    context['hasGoverningAuthority'] = "http://vivoweb.org/ontology/core#hasGoverningAuthority"
    context['hasNote'] = "http://www.w3.org/2006/vcard/ns#hasNote"
    context['description'] = "http://vivoweb.org/ontology/core#description"
    context['abstract'] = "http://purl.org/ontology/bibo/abstract"
    context['dateTimeValue'] = "http://vivoweb.org/ontology/core#dateTimeValue"
    context['dateTime'] = "http://vivoweb.org/ontology/core#dateTime"
    context['dateTimePrecision'] = "http://vivoweb.org/ontology/core#dateTimePrecision"
    context['vcardURL'] = "http://www.w3.org/2006/vcard/ns#URL"
    context['explanatory'] = "http://www.w3.org/2006/vcard/ns#Explanatory"
    context['title'] = "http://www.w3.org/2006/vcard/ns#title"
    context['overview'] = "http://vivoweb.org/ontology/core#overview"
    context['hasPublicationVenue'] = "http://vivoweb.org/ontology/core#hasPublicationVenue"
    context['publicationVenueFor'] = "http://vivoweb.org/ontology/core#publicationVenueFor"
    
    return context

